spring:
  datasource:
    url: jdbc:mysql://localhost:3306/MyAppDb?useSSL=false&allowPublicKeyRetrieval=true
    username: myapp-user
    password: password
  jpa:
    hibernate:
      ddl-auto: update